/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reptiles/create-reptil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear un reptil */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Reptil"];
                };
            };
            responses: {
                /** @description Reptil creado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error de validación */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Ya existe un reptil con ese nombre */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los reptiles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de reptiles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reptil"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un reptil por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reptil encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reptil no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/update-reptil/{reptileID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar un reptil */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Reptil"];
                };
            };
            responses: {
                /** @description Reptil actualizado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nombre duplicado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/reptiles/delete-reptil/{reptileID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar un reptil */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reptil eliminado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/{reptileID}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todas las notas de un reptil */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de notas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Note"][];
                    };
                };
                /** @description Reptil no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Crear una nota para un reptil */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            responses: {
                /** @description Nota creada correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error de validación */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/{reptileID}/notes/{noteID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una nota por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    noteID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nota encontrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Note"];
                    };
                };
                /** @description Nota no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Eliminar una nota */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    noteID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nota eliminada correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Actualizar una nota */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    noteID: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            responses: {
                /** @description Nota actualizada correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Nota no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/reptiles/{reptileID}/logPesaje": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener logs de pesaje de un reptil */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de registros de pesaje */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogPesaje"][];
                    };
                };
                /** @description Reptil no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Crear un registro de pesaje */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogPesaje"];
                };
            };
            responses: {
                /** @description Registro de pesaje creado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error de validación */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/{reptileID}/logPesaje/{logPesajeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un log de pesaje por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logPesajeID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registro de pesaje encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogPesaje"];
                    };
                };
                /** @description Registro no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Eliminar un registro de pesaje */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logPesajeID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registro eliminado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Actualizar un registro de pesaje */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logPesajeID: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogPesaje"];
                };
            };
            responses: {
                /** @description Registro actualizado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registro no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/reptiles/{reptileID}/logComidas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener logs de comida de un reptil */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de registros de comida */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogComidas"][];
                    };
                };
            };
        };
        put?: never;
        /** Crear un registro de comida */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogComidas"];
                };
            };
            responses: {
                /** @description Registro de comida creado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error de validación */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reptiles/{reptileID}/logComidas/{logComidaID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un log de comida por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logComidaID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registro de comida encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogComidas"];
                    };
                };
                /** @description Registro no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Eliminar un registro de comida */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logComidaID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registro eliminado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Actualizar un registro de comida */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reptileID: string;
                    logComidaID: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogComidas"];
                };
            };
            responses: {
                /** @description Registro actualizado correctamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Registro no encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 1 = Macho
         *     2 = Hembra
         *     3 = Desconocido
         * @enum {number}
         */
        Genre: 1 | 2 | 3;
        /** @enum {string} */
        TipoNota: "comida" | "suplemento" | "comportamiento" | "otro";
        /** @enum {string} */
        TagsNota: "calcio" | "multivitaminico" | "muda" | "comportamiento normal" | "fruta";
        /** @enum {string} */
        Unidad: "g" | "kg" | "ml" | "unidad";
        /** @enum {string} */
        TipoAlimento: "grillo" | "gusano de harina" | "gusano de coco" | "gusano rey" | "cucaracha dubia" | "cucaracha roja" | "ratón pinky" | "ratón adulto" | "otro";
        /** @enum {string} */
        MetodoAlimentacion: "manual" | "pinzas" | "libre" | "forzada" | "otro";
        /** @enum {string} */
        ContextoPesaje: "Control rutinario" | "Post muda" | "Pre cría" | "Post cría" | "Revisión por enfermedad" | "Cambio de dieta" | "Nuevo ejemplar" | "Otro";
        /** @description Usuario básico (owner poblado) */
        UserBasic: {
            /**
             * @description ID del usuario
             * @example 65a1bc23ff12a9c33b0eaaaa
             */
            _id?: string;
            /**
             * @description Nombre del usuario
             * @example Ian
             */
            name?: string;
        };
        Reptil: {
            /** @example 65a1bc23ff12a9c33b0e9999 */
            _id?: string;
            /** @example Iguana Verde */
            name: string;
            /**
             * Format: date
             * @example 2022-03-15
             */
            birthDate?: string;
            /** @example Reptil arbóreo */
            description?: string;
            genre: components["schemas"]["Genre"];
            notas?: string[];
            logPesaje?: string[];
            logComida?: string[];
            owner?: components["schemas"]["UserBasic"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Note: {
            _id?: string;
            /** @example Revisión veterinaria */
            name: string;
            /** @example Chequeo general */
            description?: string;
            type: components["schemas"]["TipoNota"];
            tags?: components["schemas"]["TagsNota"];
            /** @example 1.3 */
            weight?: number;
            /** @example 70 */
            humidity?: number;
            /** @example 28 */
            temp?: number;
            /** @description ID del reptil */
            reptil: string;
            createdBy?: components["schemas"]["UserBasic"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LogPesaje: {
            _id?: string;
            /** @example 1.45 */
            peso: number;
            unidad?: components["schemas"]["Unidad"];
            contexto?: components["schemas"]["ContextoPesaje"];
            /** @example Peso tomado en ayuno */
            observaciones?: string;
            /** @example 0.05 */
            diferencia?: number;
            /** @description ID del reptil */
            reptil: string;
            createdBy?: components["schemas"]["UserBasic"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LogComidas: {
            _id?: string;
            /** @example 5 */
            cantidad: number;
            unidad?: components["schemas"]["Unidad"];
            tipoAlimento: components["schemas"]["TipoAlimento"];
            /** @example Calcio */
            suplemento?: string;
            metodo?: components["schemas"]["MetodoAlimentacion"];
            /** @example Buen apetito */
            observaciones?: string;
            /** @example true */
            excreto?: boolean;
            apetito?: number;
            nextFeeding?: number;
            /** @description ID del reptil */
            reptil: string;
            createdBy?: components["schemas"]["UserBasic"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
